/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.*;
import java.net.*;
import java.net.Socket;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author Seok17
 */
public class ChattingRoom extends JFrame {
    private int RoomId;
    private String RoomName;
    private Socket socket;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private String name;
    private String id;
    /**
     * Creates new form ChattingRoom
     */
    public ChattingRoom() {
        this.RoomId = 0;
        this.RoomName = "방 제목 없음";
        initComponents();
        enterRoomThread(0);
    }
    
    public ChattingRoom(int Roomid, String RoomName, RoomList rt) {
        this.RoomId = Roomid;
        this.RoomName = RoomName;
        ois = rt.getOis();
        oos = rt.getOos();
        name = rt.getName();
        id = rt.getId();
        initComponents();
        enterRoomThread(Roomid);
    }
    
    public ObjectOutputStream getOos(){
        return this.oos;
    }
    public ObjectInputStream getOis(){
        return this.ois;
    }
    
    public int getId(){
        return this.RoomId;
    }
    
    public JTextArea getJta(){
        return this.showMsg;
    }
    
    public int getRoomId(){
        return this.RoomId;
    }
    
    public String getName(){
        return this.name;
    }
    
     public void enterRoomThread(int roomid){
        MultiClientThread ct =new MultiClientThread(this);
        Thread t =new Thread(ct);
        t.start();
    }
     
     public void messageMake(){
         String msg = SendText.getText();
         try{
             oos.writeObject(this.getRoomId()+"#"+this.getName()+"#"+msg);
             
         }catch(Exception e){
             e.printStackTrace();
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomNumLabel = new javax.swing.JPanel();
        SendText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showMsg = new javax.swing.JTextArea();
        RoomNameLbel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GGeTalk - Chat Room");
        setResizable(false);

        RoomNumLabel.setBackground(new java.awt.Color(54, 57, 63));

        SendText.setBackground(new java.awt.Color(64, 68, 75));
        SendText.setFont(new java.awt.Font("휴먼엑스포", 0, 18)); // NOI18N
        SendText.setForeground(new java.awt.Color(255, 255, 255));
        SendText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendTextActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(64, 68, 75));
        jButton2.setFont(new java.awt.Font("휴먼엑스포", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("보내기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        showMsg.setEditable(false);
        showMsg.setBackground(new java.awt.Color(64, 68, 75));
        showMsg.setColumns(20);
        showMsg.setFont(new java.awt.Font("휴먼엑스포", 0, 13)); // NOI18N
        showMsg.setForeground(new java.awt.Color(255, 255, 255));
        showMsg.setRows(5);
        jScrollPane2.setViewportView(showMsg);

        RoomNameLbel.setFont(new java.awt.Font("휴먼엑스포", 0, 16)); // NOI18N
        RoomNameLbel.setForeground(new java.awt.Color(255, 255, 255));
        RoomNameLbel.setText(this.RoomName);

        javax.swing.GroupLayout RoomNumLabelLayout = new javax.swing.GroupLayout(RoomNumLabel);
        RoomNumLabel.setLayout(RoomNumLabelLayout);
        RoomNumLabelLayout.setHorizontalGroup(
            RoomNumLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomNumLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomNumLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomNumLabelLayout.createSequentialGroup()
                        .addComponent(RoomNameLbel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(SendText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomNumLabelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        RoomNumLabelLayout.setVerticalGroup(
            RoomNumLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomNumLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RoomNameLbel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SendText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void SendTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendTextActionPerformed
        Object obj = evt.getSource();
        String msg = SendText.getText();
        
        if(obj == SendText){
            if(msg == null || msg.length()==0){
             JOptionPane.showMessageDialog(this, "공백은 보낼 수 없습니다.","경고",JOptionPane.WARNING_MESSAGE);
            }else{
                this.messageMake();
            }
        }
    }//GEN-LAST:event_SendTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Object obj = evt.getSource();
        String msg = SendText.getText();
        
        if(obj == SendText){
            if(msg == null || msg.length()==0){
             JOptionPane.showMessageDialog(this, "공백은 보낼 수 없습니다.","경고",JOptionPane.WARNING_MESSAGE);
            }else{
                this.messageMake();
                
                SendText.setText("");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChattingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChattingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChattingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChattingRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChattingRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RoomNameLbel;
    private javax.swing.JPanel RoomNumLabel;
    private javax.swing.JTextField SendText;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea showMsg;
    // End of variables declaration//GEN-END:variables
}
